apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    chart: wordpress
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.2.33
    helm:
      releaseName: wordpress
      valueFiles:
        - values.yaml
        # - https://github.com/peteriselksnis/argocd-sample-project-wp/external/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wp