apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami/wordpress
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.1.1
    helm:
      releaseName: wordpress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal